# Generated by Django 2.1.7 on 2019-06-10 14:54

from django.db import migrations, models
import django.views.generic.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('qrcode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UrlPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(django.views.generic.base.TemplateView, models.Model),
        ),
        migrations.CreateModel(
            name='Vcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=100)),
                ('security', models.CharField(choices=[('Password', 'No password required'), ('WPA', 'WPA/WPA2'), ('WEP', 'WEP')], max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('qrcode', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WifiPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(django.views.generic.base.TemplateView, models.Model),
        ),
    ]
